-- zadanie 1
DROP TABLE FIGURY
CREATE TABLE FIGURY(ID number(1), KSZTALT MDSYS.SDO_GEOMETRY);

INSERT INTO FIGURY VALUES (1, MDSYS.SDO_GEOMETRY(2003,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,4), SDO_ORDINATE_ARRAY(3,5,5,7,7,5)))


INSERT INTO FIGURY VALUES (2, MDSYS.SDO_GEOMETRY(2003,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,3), SDO_ORDINATE_ARRAY(1,1,5,5)))
SELECT * FROM FIGURY


INSERT INTO FIGURY VALUES (3, MDSYS.SDO_GEOMETRY(2002,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2), SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)))

INSERT INTO FIGURY VALUES (4, MDSYS.SDO_GEOMETRY(2003,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,4), SDO_ORDINATE_ARRAY(3,5,7,5,5,5,5,7) ))

SELECT * FROM FIGURY

select SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT,0.01) FROM FIGURY

DELETE FROM FIGURY WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.01) NOT LIKE 'TRUE';

COMMIT
