-- zadanie 1
SELECT * FROM USER_SDO_GEOM_METADATA

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='FIGURY'

INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('FIGURY', 'KSZTALT', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,10,0.01), MDSYS.SDO_DIM_ELEMENT('Y',0,10,0.01)), NULL);

SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000,8192,10,2,0) FROM FIGURY


SELECT  * FROM all_indexes WHERE table_name = 'FIGURY';

DROP INDEX FIGURY_IDX;

CREATE INDEX FIGURY_IDX ON FIGURY(KSZTALT) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

SELECT ID FROM FIGURY
WHERE SDO_FILTER(KSZTALT, SDO_GEOMETRY(2001, null, SDO_POINT_TYPE(3,3,null), null, null)) = 'TRUE';

SELECT ID FROM FIGURY
WHERE SDO_RELATE(KSZTALT, SDO_GEOMETRY(2001, null, SDO_POINT_TYPE(3,3,null), null, null), 'mask=ANYINTERACT') = 'TRUE';


-- zadanie 2
SELECT CITY_NAME AS MIASTO, SDO_NN_DISTANCE(1) AS ODL FROM MAJOR_CITIES
WHERE CITY_NAME != 'Warsaw' and SDO_NN(GEOM, (SELECT GEOM FROM MAJOR_CITIES WHERE CITY_NAME = 'Warsaw'), 'sdo_num_res=10 unit=km', 1) = 'TRUE';


SELECT CITY_NAME AS MIASTO FROM MAJOR_CITIES
WHERE CITY_NAME != 'Warsaw' and SDO_WITHIN_DISTANCE(GEOM,(SELECT GEOM FROM MAJOR_CITIES WHERE CITY_NAME = 'Warsaw'), 'distance=100 unit=km') = 'TRUE';


SELECT * FROM MAJOR_CITIES;
SELECT * FROM COUNTRY_BOUNDARIES;
SELECT CNTRY_NAME AS KRAJ, CITY_NAME AS MIASTO FROM MAJOR_CITIES
WHERE SDO_RELATE(GEOM, (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME = 'Slovakia'), 'mask=ANYINTERACT') = 'TRUE';


SELECT CNTRY_NAME AS PANSTWO, SDO_NN_DISTANCE(1) AS ODL FROM COUNTRY_BOUNDARIES
WHERE CNTRY_NAME NOT LIKE 'Poland' AND SDO_NN(GEOM, (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME = 'Poland'), 'unit=km', 1) = 'TRUE' AND
    SDO_RELATE(GEOM, (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME='Poland'), 'mask=TOUCH') = 'FALSE';


-- zadanie 3
SELECT SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(GEOM, GEOM, 1), 1, 'unit=km') FROM COUNTRY_BOUNDARIES;
SELECT CNTRY_NAME AS PANSTWO, SDO_GEOM.SDO_LENGTH(GEOM, 1) FROM COUNTRY_BOUNDARIES
WHERE CNTRY_NAME NOT LIKE 'Poland' AND SDO_RELATE(GEOM, (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME='Poland'), 'mask=TOUCH') = 'TRUE';


SELECT CNTRY_NAME AS PANSTWO, SDO_GEOM.SDO_AREA(GEOM, 1, 'unit=SQ_KM')
FROM COUNTRY_BOUNDARIES
WHERE CNTRY_NAME NOT LIKE 'Poland' AND SDO_RELATE(GEOM, (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME='Poland'), 'mask=TOUCH') = 'TRUE'
ORDER BY 2 DESC FETCH NEXT 1 ROWS ONLY;


SELECT SDO_GEOM.SDO_AREA( SDO_GEOM.SDO_MBR(SDO_GEOM.SDO_UNION(A.GEOM, B.GEOM, 0.01)), 1, 'unit=SQ_KM') SQ_KM
FROM MAJOR_CITIES A, MAJOR_CITIES B
WHERE A.CITY_NAME = 'Warsaw' AND B.CITY_NAME = 'Lodz';


SELECT B.CITY_NAME, A.CNTRY_NAME FROM COUNTRY_BOUNDARIES A, MAJOR_CITIES B
WHERE A.CITY_NAME = B.CITY_NAME AND SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(A.GEOM, 1), B.GEOM, 1) = (
        SELECT MIN(SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(A.GEOM, 1), B.GEOM, 1))
        FROM COUNTRY_BOUNDARIES A, MAJOR_CITIES B
        WHERE A.CNTRY_NAME = B.CNTRY_NAME);


SELECT NAME, SUM(LENGTH) DLUGOSC
FROM (
    SELECT B.name, SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, B.GEOM, 1), 1, 'unit=KM') LENGTH
    FROM COUNTRY_BOUNDARIES A, RIVERS B
    WHERE SDO_RELATE(A.GEOM, SDO_GEOMETRY(2001, 8307, B.GEOM.SDO_POINT, B.GEOM.SDO_ELEM_INFO,
            B.GEOM.SDO_ORDINATES), 'mask=ANYINTERACT') = 'TRUE' AND A.CNTRY_NAME = 'Poland')
GROUP BY NAME;
